### ISSUE TITLE
configure: error: Could not found aarx.core.  Is amino installed?

### ISSUE THREAD

**Issue by clemense** [KavrakiLab/tmkit#1]
I built and installed amino. 
But I cannot configure tmkit due to:

checking for aarx.core... no
configure: error: Could not found aarx.core.  Is amino installed?

What is this aarx.core? Do I have to enable something to during the amino build?

**Comment by ndantam** [comment]
Yes, aarx.core is built as part of amino.

Check the  output of amino's ./configure or config.log so see what 
happened.  Offhand, maybe you don't have SBCL installed?

-ntd

On 03/20/2018 09:58 PM, clemense wrote:
> I built and installed amino.
> But I cannot configure tmkit due to:
> 
> checking for aarx.core... no
> configure: error: Could not found aarx.core.  Is amino installed?
> 
> What is this aarx.core? Do I have to enable something to during the amino build?
> 


-- 
Neil T. Dantam, Ph.D.
Assistant Professor
Department of Computer Science
Colorado School of Mines
http://www.mines.edu/~ndantam

**Comment by clemense** [comment]
Thanks!
I didn't miss sbcl but Quicklisp.

**Comment by ndantam** [comment]
Great!
