### ISSUE TITLE
Error during make 

### ISSUE THREAD

**Issue by Reluigi** [KavrakiLab/tmkit#12]
While doing make I keep having this error:
```
Error opening shared object "libamino.so":
  libamino.so: cannot open shared object file: No such file or directory.
```
How can I fix it?

**Comment by ndantam** [comment]
Have you installed amino (https://github.com/golems/amino)?  Sometimes, you need an `ldconfig` for the linker to pick up shared libraries in /usr/local.

**Comment by Reluigi** [comment]
Yes I installed Amino without errors. I tried to look for that file manually but it seems that it isn't in the shared libraries nor in the installed amino folder

**Comment by ndantam** [comment]
On most Linux distributions, libamino will (by default) be installed to /usr/local/lib/.

For reference, you can see the dockerfiles in amino/script/docker for the commands to install amino on debian and ubuntu.

**Comment by Reluigi** [comment]
Ok I fixed it. I manually added the path to the `.bashrc` file and it compiled. Thanks!

**Comment by MennatallahRihan** [comment]
I have the same exact issue, can you tell me what you wrote exactly in the `.bashrc` file?

**Comment by ndantam** [comment]
Please try a `sudo ldconfig` and see if that resolves the problem.
