### ISSUE TITLE
Error with openGL running the tutorial

### ISSUE THREAD

**Issue by Reluigi** [KavrakiLab/tmkit#13]
I was trying to run the tutorial but when I run 
` aarxc --gui < path to baxter.urdf>`

I get this error:
```
WARNING: OpenGL multisample anti-aliasing disabled.
OpenGL context could not be created! SDL Error: Could not create GL context
fatal error encountered in SBCL pid 21798(tid 140737353824000):
SIGABRT received.
```

I'm currently running the tutorial in a ubuntu virtual machine on macOS; is this problem related to that?

**Comment by ndantam** [comment]
You probably need to set up OpenGL / Direct Rendering in the VM.  For 
some VMs, there are guest drivers ("guest additions") you can install.

-ntd

On 7/8/19 10:02 AM, Luigi wrote:
> I was trying to run the tutorial but when I run
> ` aarxc --gui < path to baxter.urdf>`
> 
> I get this error:
> ```
> WARNING: OpenGL multisample anti-aliasing disabled.
> OpenGL context could not be created! SDL Error: Could not create GL context
> fatal error encountered in SBCL pid 21798(tid 140737353824000):
> SIGABRT received.
> ```
> 
> I'm currently running the tutorial in a ubuntu virtual machine on macOS; is this problem related to that?
> 
> 


-- 
Neil T. Dantam, Ph.D.
Assistant Professor
Department of Computer Science
Colorado School of Mines
http://www.mines.edu/~ndantam

**Comment by Reluigi** [comment]
Fixed, it was related to some settings about 3D acceleration of my virtual machine. Thank you!
